baseURL = 'https://datho7561.github.io/'
languageCode = 'en-us'
title = "datho7561's blog"
theme = ['github.com/imfing/hextra']

[outputs]
home = ['html', 'rss']

[params.theme]
default = "light"
displayToggle = false

[params.navbar]
displayLogo = false

[params.footer]
enable = false

[[menu.main]]
name = "About"
pageRef = "about"
weight = 1

[[menu.main]]
name = "Blog"
pageRef = "blog"
weight = 1

[[menu.main]]
name = "Video Game Kanban"
pageRef = "video-game-kanban"
weight = 1

[[menu.main]]
name = "Blog RSS"
url = "/index.xml"
params = { icon = "rss" }

[[menu.main]]
name = "GitHub"
url = "https://github.com/datho7561"
params = { icon = "github" }

[[menu.main]]
name = "Codeberg"
url = "https://codeberg.org/datho7561"
params = { icon = "codeberg" }

[[menu.main]]
name = "Mastodon"
url = "https://mastodon.online/@datho7561"
params = { icon = "mastodon" }

[[menu.main]]
name = "BlueSky"
url = "https://bsky.app/profile/datho7561.dev"
params = { icon = "bluesky" }

[[menu.main]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/david-thompson-sfwr/"
params = { icon = "linkedin" }


